// Core OpenXR functions
OXR_PROC(xrGetInstanceProcAddr)
OXR_PROC(xrEnumerateInstanceExtensionProperties)
OXR_PROC(xrCreateInstance)
OXR_PROC(xrDestroyInstance)
OXR_PROC(xrGetSystem)
OXR_PROC(xrResultToString)
OXR_PROC(xrPollEvent)

// Session and frame functions
OXR_PROC(xrCreateSession)
OXR_PROC(xrDestroySession)
OXR_PROC(xrBeginSession)
OXR_PROC(xrEndSession)
OXR_PROC(xrWaitFrame)
OXR_PROC(xrBeginFrame)
OXR_PROC(xrEndFrame)
OXR_PROC(xrCreateReferenceSpace)
OXR_PROC(xrDestroySpace)
OXR_PROC(xrLocateViews)
OXR_PROC(xrEnumerateViewConfigurationViews)
OXR_PROC(xrEnumerateSwapchainFormats)
OXR_PROC(xrCreateSwapchain)
OXR_PROC(xrDestroySwapchain)
OXR_PROC(xrEnumerateSwapchainImages)
OXR_PROC(xrAcquireSwapchainImage)
OXR_PROC(xrWaitSwapchainImage)
OXR_PROC(xrReleaseSwapchainImage)

// Vulkan bootstrap / query functions
OXR_OPT_PROC(xrGetVulkanInstanceExtensionsKHR)
OXR_OPT_PROC(xrGetVulkanDeviceExtensionsKHR)
OXR_OPT_PROC(xrGetVulkanGraphicsRequirementsKHR)
OXR_OPT_PROC(xrGetVulkanGraphicsRequirements2KHR)
OXR_OPT_PROC(xrGetVulkanGraphicsDeviceKHR)
OXR_OPT_PROC(xrGetVulkanGraphicsDevice2KHR)
