#!/usr/bin/env python3
import argparse
import hashlib
import json
import os
import re
import struct
import zipfile
from pathlib import Path


MOD_ID = "doom-voxels"
MOD_TITLE = "Voxel Doom II"
VERSION = "2.4"
VERSION_KEY = "2.4-f16e1577"
ZIP_FILENAME = "VoxelDoom_v2.4.pk3.zip"
PK3_FILENAME = "VoxelDoom_v2.4.pk3"
EXPECTED_ZIP_MD5 = "f16e15778600e95c99399d58f4eeb1ed"
OUTPUT_PK3 = "voxel-doom-ii-2.4-rt.pk3"
DOOM_IWAD_FILENAMES = {
    "doom.wad",
    "doom1.wad",
    "doom2.wad",
    "doomu.wad",
    "freedm.wad",
    "freedoom1.wad",
    "freedoom2.wad",
    "plutonia.wad",
    "tnt.wad",
}


def digest_file(path, algorithm):
    digest = hashlib.new(algorithm)
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def default_library():
    return Path(os.environ.get("RT_MODS_DIR", "~/Games/gzdoom-rt/mods")).expanduser()


def default_iwad_dir():
    return Path(os.environ.get("DOOMWADDIR", "~/Games/gzdoom-rt/wad")).expanduser()


def version_dir(library):
    return library / MOD_ID / VERSION_KEY


def manifest_path(rt_dir):
    return rt_dir / "autoload" / ".rt-mods" / f"{MOD_ID}.json"


def normalize_rel(path):
    return path.as_posix().lstrip("/")


def validate_library_source(library):
    base = version_dir(library)
    zip_path = base / ZIP_FILENAME
    pk3_path = base / PK3_FILENAME

    if zip_path.is_file():
        md5 = digest_file(zip_path, "md5")
        if md5 != EXPECTED_ZIP_MD5:
            raise SystemExit(
                f"Checksum mismatch for {zip_path}\n"
                f"  expected md5: {EXPECTED_ZIP_MD5}\n"
                f"  actual md5:   {md5}"
            )

    if not pk3_path.is_file():
        raise SystemExit(
            "No Voxel Doom II PK3 source found.\n"
            f"Expected:\n  {pk3_path}\n"
            f"Place the downloaded {ZIP_FILENAME} in:\n  {base}\n"
            f"Then extract {PK3_FILENAME} from it into the same directory."
        )

    return pk3_path


def validate_pk3(path):
    try:
        with zipfile.ZipFile(path, "r") as zf:
            names = [info.filename.lower() for info in zf.infolist() if not info.is_dir()]
    except zipfile.BadZipFile:
        raise SystemExit(f"Source is not a valid PK3/ZIP archive: {path}")

    has_voxels = any(name.startswith("voxels/") for name in names)
    has_voxeldef = any(name == "voxeldef" or name == "voxeldef.txt" for name in names)
    if not has_voxels or not has_voxeldef:
        raise SystemExit(
            f"{path} does not look like Voxel Doom II; expected voxels/ and VOXELDEF/VOXELDEF.txt"
        )


def read_wad_sprite_names(path):
    names = set()
    with path.open("rb") as f:
        header = f.read(12)
        if len(header) != 12:
            return names
        _magic, lump_count, directory_offset = struct.unpack("<4sii", header)
        f.seek(directory_offset)
        for _ in range(lump_count):
            entry = f.read(16)
            if len(entry) != 16:
                break
            name = entry[8:16].split(b"\0", 1)[0].decode("ascii", "ignore").upper()
            if len(name) >= 4:
                names.add(name[:4])
    return names


def collect_doom_sprite_names(iwad_dir):
    names = set()
    if not iwad_dir.is_dir():
        return names
    for wad in iwad_dir.iterdir():
        if wad.name.lower() in DOOM_IWAD_FILENAMES:
            names.update(read_wad_sprite_names(wad))
    return names


def pk3_voxel_names(zf, voxeldef_name):
    names = set()
    lower_voxeldef = voxeldef_name.lower()
    slash = lower_voxeldef.rfind("/")
    prefix = "voxels/" if slash < 0 else f"{lower_voxeldef[:slash + 1]}voxels/"
    for info in zf.infolist():
        lower = info.filename.lower()
        if lower.startswith(prefix) and lower.endswith(".kvx"):
            names.add(lower.rsplit("/", 1)[-1][:-4])
    return names


def strip_comments(text):
    text = re.sub(r"(?ms)/\*.*?\*/", "", text)
    return re.sub(r"//.*", "", text)


def sanitize_voxeldef(text, sprite_names, voxel_names):
    entry_re = re.compile(
        r"(?ms)(?P<sprites>(?:[A-Za-z0-9_]{4,5}\s+)*[A-Za-z0-9_]{4,5})"
        r'\s*=\s*"(?P<voxel>[^"]+)"\s*(?P<block>\{.*?\})?'
    )
    kept = []
    dropped = []

    for match in entry_re.finditer(strip_comments(text)):
        sprites = match.group("sprites").split()
        voxel = match.group("voxel")
        block = match.group("block") or "{}"
        valid_sprites = [s for s in sprites if len(s) in (4, 5) and s[:4].upper() in sprite_names]

        if valid_sprites and voxel.lower() in voxel_names:
            kept.append(f'{" ".join(valid_sprites)} = "{voxel}" {block}'.rstrip())
        else:
            dropped.append((sprites, voxel))

    header = "// Generated by tools/rt-mods/recipes/doom_voxels.py\n"
    header += "// Removed VOXELDEF entries whose sprites or voxel files are absent for this Doom setup.\n\n"
    return header + "\n\n".join(kept) + "\n", dropped


def bundled_cheello_scripts_exist(rt_dir):
    return any(
        path.exists()
        for path in [
            rt_dir / "wad" / "zscript" / "CheelloVox",
            rt_dir / "wad" / "filter" / "doom.id.doom2" / "zscript" / "CheelloVox",
        ]
    )


def should_strip_for_assets_only(name):
    lower = name.lower()
    base = lower.rsplit("/", 1)[-1]
    script_config_lumps = {
        "cvarinfo",
        "cvarinfo.lmp",
        "decaldef",
        "decaldef.lmp",
        "decaldef.txt",
        "decorate",
        "decorate.lmp",
        "decorate.txt",
        "gldefs",
        "gldefs.lmp",
        "gldefs.txt",
        "keyconf",
        "keyconf.lmp",
        "keyconf.txt",
        "language",
        "language.enu",
        "language.lmp",
        "language.txt",
        "mapinfo",
        "mapinfo.lmp",
        "mapinfo.txt",
        "menudef",
        "menudef.lmp",
        "menudef.txt",
        "zscript",
        "zscript.txt",
        "zscript.zc",
    }
    if base in script_config_lumps:
        return True
    if lower.startswith("zscript/"):
        return True
    if lower.startswith("filter/") and "/zscript" in lower:
        return True
    return False


def is_voxeldef(name):
    base = name.lower().rsplit("/", 1)[-1]
    return base == "voxeldef" or base == "voxeldef.txt"


def build_runtime_pk3(source_pk3, target_pk3, mode, sprite_names):
    stripped = []
    dropped_voxeldef = []
    target_pk3.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(source_pk3, "r") as src, zipfile.ZipFile(
        target_pk3, "w", compression=zipfile.ZIP_DEFLATED
    ) as dst:
        voxel_names_by_def = {}
        for info in src.infolist():
            if info.is_dir():
                continue
            if mode == "assets-only" and should_strip_for_assets_only(info.filename):
                stripped.append(info.filename)
                continue
            if mode == "assets-only" and is_voxeldef(info.filename):
                voxel_names = voxel_names_by_def.setdefault(info.filename, pk3_voxel_names(src, info.filename))
                text = src.read(info.filename).decode("utf-8", "replace")
                sanitized, dropped = sanitize_voxeldef(text, sprite_names, voxel_names)
                dropped_voxeldef.extend((info.filename, sprites, voxel) for sprites, voxel in dropped)
                dst.writestr(info, sanitized)
                continue
            dst.writestr(info, src.read(info.filename))

        dst.writestr(
            "RT_MOD_INFO.txt",
            "\n".join(
                [
                    f"mod_id={MOD_ID}",
                    f"title={MOD_TITLE}",
                    f"version={VERSION}",
                    f"source={source_pk3.name}",
                    f"mode={mode}",
                    "generated_by=tools/rt-mods/recipes/doom_voxels.py",
                    "",
                ]
            ),
        )

    return stripped, dropped_voxeldef


def write_manifest(rt_dir, source_pk3, target_pk3, mode, stripped, dropped_voxeldef):
    path = manifest_path(rt_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "mod_id": MOD_ID,
        "title": MOD_TITLE,
        "version": VERSION,
        "source": str(source_pk3),
        "source_sha256": digest_file(source_pk3, "sha256"),
        "mode": mode,
        "installed_files": [normalize_rel(target_pk3.relative_to(rt_dir))],
        "stripped_lumps": stripped,
        "dropped_voxeldef_entries": len(dropped_voxeldef),
    }
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def remove_path_if_owned(rt_dir, relpath):
    target = rt_dir / relpath
    try:
        target.relative_to(rt_dir)
    except ValueError:
        raise RuntimeError(f"Refusing to remove path outside RT dir: {target}")
    if target.exists() or target.is_symlink():
        target.unlink()
        return target
    return None


def uninstall(rt_dir):
    removed = []
    path = manifest_path(rt_dir)

    if path.is_file():
        data = json.loads(path.read_text(encoding="utf-8"))
        for relpath in data.get("installed_files", []):
            removed_path = remove_path_if_owned(rt_dir, relpath)
            if removed_path:
                removed.append(removed_path)
        path.unlink()
        removed.append(path)
    else:
        for relpath in [
            Path("autoload") / "doom" / OUTPUT_PK3,
            Path("autoload") / "doom.id" / OUTPUT_PK3,
            Path("autoload") / "doom.id.doom2" / OUTPUT_PK3,
        ]:
            removed_path = remove_path_if_owned(rt_dir, relpath)
            if removed_path:
                removed.append(removed_path)

    return removed


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate or experimentally install fresh Voxel Doom II from the external RT mod library."
    )
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[3]))
    parser.add_argument(
        "--library",
        default=str(default_library()),
        help="External mod library. Defaults to $RT_MODS_DIR or ~/Games/gzdoom-rt/mods.",
    )
    parser.add_argument(
        "--rt-dir",
        default=os.environ.get("RT_DATA_DIR"),
        help="RT data directory. Defaults to <repo-root>/rt.",
    )
    parser.add_argument(
        "--iwad-dir",
        default=str(default_iwad_dir()),
        help="Directory containing Doom-family IWADs for VOXELDEF sanitation. Defaults to $DOOMWADDIR or ~/Games/gzdoom-rt/wad.",
    )
    parser.add_argument(
        "--mode",
        choices=["auto", "full", "assets-only"],
        default="auto",
        help="Only used with --install-kvx. full loads upstream scripts too; assets-only avoids duplicate Cheello ZScript when RT data already has it.",
    )
    parser.add_argument(
        "--install-kvx",
        action="store_true",
        help="Experimental: generate an autoload PK3 from the fresh KVX package. Doom RT normally uses bundled converted voxel replacements instead.",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove the installed Voxel Doom II runtime package and install manifest.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    rt_dir = Path(args.rt_dir).resolve() if args.rt_dir else repo_root / "rt"
    library = Path(args.library).expanduser().resolve()
    iwad_dir = Path(args.iwad_dir).expanduser().resolve()

    if args.uninstall:
        removed = uninstall(rt_dir)
        if removed:
            print("Removed Voxel Doom II runtime files:")
            for path in removed:
                print(f"  {path}")
        else:
            print("No Voxel Doom II runtime files found.")
        return

    source_pk3 = validate_library_source(library)
    source_pk3 = source_pk3.resolve()
    if not source_pk3.is_file():
        raise SystemExit(f"Missing source PK3: {source_pk3}")

    validate_pk3(source_pk3)

    if not args.install_kvx:
        print(f"Validated {MOD_TITLE} {VERSION} source:")
        print(f"  {source_pk3}")
        print("No runtime package was installed.")
        print("Doom RT already ships converted Doom voxel replacements in rt/replace;")
        print("autoloading fresh Voxel Doom II KVX assets can misalign rotations with that older RT integration.")
        print("Use --install-kvx only for experimental testing.")
        return

    mode = args.mode
    if mode == "auto":
        mode = "assets-only" if bundled_cheello_scripts_exist(rt_dir) else "full"

    target_pk3 = rt_dir / "autoload" / "doom" / OUTPUT_PK3
    old_removed = uninstall(rt_dir)
    sprite_names = collect_doom_sprite_names(iwad_dir) if mode == "assets-only" else set()
    if mode == "assets-only" and not sprite_names:
        raise SystemExit(f"No Doom-family IWAD sprites found for VOXELDEF sanitation in: {iwad_dir}")

    stripped, dropped_voxeldef = build_runtime_pk3(source_pk3, target_pk3, mode, sprite_names)
    manifest = write_manifest(rt_dir, source_pk3, target_pk3, mode, stripped, dropped_voxeldef)

    if old_removed:
        print(f"Replaced previous Voxel Doom II install ({len(old_removed)} file/manifest path(s) removed).")
    print(f"Installed {MOD_TITLE} {VERSION} for RT:")
    print(f"  {target_pk3}")
    print(f"  source: {source_pk3}")
    print(f"  mode: {mode}")
    print(f"  manifest: {manifest}")
    if stripped:
        print(f"  stripped {len(stripped)} script/config lump(s) to avoid duplicate bundled Cheello code.")
    if dropped_voxeldef:
        print(f"  dropped {len(dropped_voxeldef)} incompatible VOXELDEF entry/entries.")


if __name__ == "__main__":
    main()
