#!/usr/bin/env python3
import argparse
import hashlib
import os
import re
import struct
import sys
import warnings
import zipfile
from pathlib import Path


VARIANTS = {
    "lite": {
        "filename": "reikallravenvoxelslite.pk3",
        "sha256": "03da4e089a9577002050cab94db6c5a02747d71a8ca08951d902bbaae03e67d9",
        "version_key": "reikall-lite-03da4e08",
    },
    "full": {
        "filename": "reikallhereticvoxels.pk3",
        "sha256": "f55ce7cd1de4708dd4e78fb9e5f74a1cb4a7b8edffef0ee6d0a1e22ef254a6b9",
        "version_key": "reikall-full-f55ce7cd",
    },
}

MOD_ID = "heretic-voxels"
BEGIN_MARKER = f"// BEGIN RT MOD {MOD_ID}"
END_MARKER = f"// END RT MOD {MOD_ID}"
LOCAL_PK3_NAMES = [
    "reikallravenvoxelslite.pk3",
    "reikallhereticvoxels.pk3",
    "reikallravenvoxelslite-rt.pk3",
    "reikallhereticvoxels-rt.pk3",
]


warnings.filterwarnings("ignore", message="Duplicate name:.*", category=UserWarning)


def default_library():
    return Path(os.environ.get("RT_MODS_DIR", "~/Games/gzdoom-rt/mods")).expanduser()


def source_path(library, variant):
    return library / MOD_ID / variant["version_key"] / variant["filename"]


def default_heretic_iwad():
    return Path(os.environ.get("HERETIC_IWAD", "~/Games/gzdoom-rt/wad/heretic.wad")).expanduser()


def sha256_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_iwad_sprite_names(path):
    names = set()
    with path.open("rb") as f:
        header = f.read(12)
        if len(header) != 12:
            return names
        _magic, lump_count, directory_offset = struct.unpack("<4sii", header)
        f.seek(directory_offset)
        for _ in range(lump_count):
            entry = f.read(16)
            if len(entry) != 16:
                break
            name = entry[8:16].split(b"\0", 1)[0].decode("ascii", "ignore").upper()
            if len(name) >= 4:
                names.add(name[:4])
    return names


def pk3_sprite_names(zf):
    names = set()
    for info in zf.infolist():
        lower = info.filename.lower()
        if lower.startswith("sprites/") and not lower.endswith("/"):
            base = lower.rsplit("/", 1)[-1].split(".", 1)[0]
            if len(base) >= 4:
                names.add(base[:4].upper())
    return names


def pk3_voxel_names(zf):
    names = set()
    for info in zf.infolist():
        lower = info.filename.lower()
        if lower.startswith("voxels/") and lower.endswith(".kvx"):
            names.add(lower.rsplit("/", 1)[-1][:-4])
    return names


def pk3_voxel_entries(zf):
    names = []
    seen = set()
    for info in zf.infolist():
        lower = info.filename.lower()
        if lower.startswith("voxels/") and lower.endswith(".kvx"):
            name = lower.rsplit("/", 1)[-1][:-4].upper()
            if name not in seen:
                names.append(name)
                seen.add(name)
    return names


def texture_name_for_voxel(voxel):
    voxel = voxel.upper()
    if voxel:
        voxel = voxel[:-1]
    return "vx_" + voxel


def strip_line_comments(text):
    return re.sub(r"//.*", "", text)


def sanitize_voxeldef(text, sprite_names, voxel_names):
    entry_re = re.compile(
        r"(?ms)(?P<sprites>(?:[A-Za-z0-9_]{4,5}\s+)*[A-Za-z0-9_]{4,5})"
        r'\s*=\s*"(?P<voxel>[^"]+)"\s*(?P<block>\{.*?\})?'
    )
    kept = []
    kept_aliases = []
    dropped = []

    for match in entry_re.finditer(strip_line_comments(text)):
        sprites = match.group("sprites").split()
        voxel = match.group("voxel")
        block = match.group("block") or ""
        valid_sprites = [s for s in sprites if len(s) in (4, 5) and s[:4].upper() in sprite_names]

        if valid_sprites and voxel.lower() in voxel_names:
            kept.append(f'{" ".join(valid_sprites)} = "{voxel}"\n{block}\n'.rstrip())
            kept_aliases.append((texture_name_for_voxel(voxel), [s.upper() for s in valid_sprites]))
        else:
            dropped.append((sprites, voxel))

    header = "// Generated by tools/rt-mods/recipes/heretic_voxels.py\n"
    header += "// Removed VOXELDEF entries whose sprites or voxel files are absent for this Heretic setup.\n\n"
    return header + "\n\n".join(kept) + "\n", kept_aliases, dropped


def sprite_texture_candidates(sprite):
    sprite = sprite.upper()
    if len(sprite) == 5:
        return [sprite + "0", sprite[:4]]
    if len(sprite) == 4:
        return [sprite + chr(frame) + "0" for frame in range(ord("A"), ord("Z") + 1)] + [sprite]
    return []


def parse_texture_entries(text):
    entries = {}
    for match in re.finditer(r'\{[^{}]*"textureName"\s*:\s*"([^"]+)"[^{}]*\}', text):
        entries.setdefault(match.group(1), match.group(0))
    return entries


def unique_backup(path, suffix):
    backup = path.with_name(path.name + suffix)
    if not backup.exists():
        return backup
    for index in range(1, 1000):
        candidate = path.with_name(f"{path.name}{suffix}.{index}")
        if not candidate.exists():
            return candidate
    raise RuntimeError(f"Could not allocate backup filename for {path}")


def remove_marked_block(text):
    marker_re = re.compile(
        r"(?ms)^[ \t]*" + re.escape(BEGIN_MARKER) + r"\n.*?^[ \t]*" + re.escape(END_MARKER) + r"\n?"
    )
    return marker_re.subn("", text)


def remove_legacy_alias_entries(text, alias_names):
    if not alias_names:
        return text, 0

    names_re = "|".join(re.escape(name) for name in sorted(alias_names, key=len, reverse=True))
    entry_re = re.compile(
        r'(?m)^[ \t]*,?[ \t]*\{[^{}\n]*"textureName"\s*:\s*"(' + names_re + r')"[^{}\n]*\}[ \t]*\n?'
    )
    return entry_re.subn("", text)


def normalize_array_entry(entry):
    entry = entry.strip()
    if entry.startswith(","):
        return "    " + entry
    return "    ,   " + entry


def parse_gldefs_metadata(text):
    text = strip_line_comments(text)
    lights = {}
    for match in re.finditer(
        r"(?mis)^\s*(?:pointlight|flickerlight\d*|pulselight)\s+([A-Za-z0-9_]+)\s*\{(.*?)^\s*\}",
        text,
    ):
        name, body = match.group(1), match.group(2)
        color_match = re.search(r"(?im)^\s*color\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)", body)
        size_match = re.search(r"(?im)^\s*size\s+([0-9.]+)", body)
        color = tuple(float(v) for v in color_match.groups()) if color_match else (1.0, 1.0, 1.0)
        size = float(size_match.group(1)) if size_match else 48.0
        lights[name] = (color, size)

    frame_meta = {}
    for match in re.finditer(r"(?mis)^\s*object\s+[A-Za-z0-9_]+\s*\{(.*?)^\s*\}", text):
        body = match.group(1)
        for frame, light in re.findall(r"(?i)frame\s+([A-Z0-9_]+)\s*\{\s*light\s+([A-Za-z0-9_]+)", body):
            if light not in lights:
                continue
            color, size = lights[light]
            color_hex = "".join(f"{max(0, min(255, int(v * 255 + 0.5))):02x}" for v in color)
            intensity = max(80, min(3000, int(size * 12.5 + 0.5)))
            frame_meta.setdefault(
                frame.upper(),
                '    ,   {{ "textureName":"{{name}}"    ,"emissiveMult":0.2     ,"noShadow":true  ,"lightIntensity":{:<5d},"lightColorHEX":"{}" }}'.format(intensity, color_hex),
            )
    return frame_meta


def collect_alias_names_from_pk3(path):
    try:
        with zipfile.ZipFile(path, "r") as zf:
            return {texture_name_for_voxel(name) for name in pk3_voxel_entries(zf)}
    except (FileNotFoundError, zipfile.BadZipFile):
        return set()


def build_texture_alias_entries(text, aliases, gldefs_meta):
    existing = parse_texture_entries(text)
    additions = []
    seen_aliases = set()

    for alias_name, sprites in aliases:
        if alias_name in existing or alias_name in seen_aliases:
            continue

        source_entry = None
        generated_entry = None
        for sprite in sprites:
            for candidate in sprite_texture_candidates(sprite):
                if candidate in existing:
                    source_entry = existing[candidate]
                    break
                frame_key = candidate[:-1] if candidate.endswith("0") else candidate
                if frame_key in gldefs_meta:
                    generated_entry = gldefs_meta[frame_key]
                    break
            if source_entry or generated_entry:
                break

        if source_entry:
            additions.append(
                normalize_array_entry(
                    re.sub(r'("textureName"\s*:\s*")[^"]+(")', rf"\1{alias_name}\2", source_entry, count=1)
                )
            )
            seen_aliases.add(alias_name)
        elif generated_entry:
            additions.append(normalize_array_entry(generated_entry.replace("{name}", alias_name)))
            seen_aliases.add(alias_name)

    return additions


def upsert_texture_aliases(path, aliases, gldefs_meta):
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return [], 0

    alias_names = {alias_name for alias_name, _sprites in aliases}
    cleaned_text, removed_blocks = remove_marked_block(text)
    cleaned_text, removed_legacy = remove_legacy_alias_entries(cleaned_text, alias_names)
    additions = build_texture_alias_entries(cleaned_text, aliases, gldefs_meta)

    new_text = cleaned_text
    if not additions:
        removed_count = removed_blocks + removed_legacy
        if removed_count:
            backup = unique_backup(path, ".before-heretic-voxels")
            backup.write_text(text, encoding="utf-8")
            path.write_text(new_text, encoding="utf-8")
        return [], removed_count

    insertion = BEGIN_MARKER + "\n" + "\n".join(additions) + "\n" + END_MARKER + "\n"
    new_text, count = re.subn(r"(?m)^(\s*\]\s*)$", insertion + r"\1", new_text, count=1)
    if count != 1:
        raise RuntimeError(f"Could not find textures.json array close in {path}")

    backup = unique_backup(path, ".before-heretic-voxels")
    backup.write_text(text, encoding="utf-8")
    path.write_text(new_text, encoding="utf-8")
    return additions, removed_blocks + removed_legacy


def remove_texture_aliases(path, alias_names):
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return 0, 0

    new_text, removed_blocks = remove_marked_block(text)
    new_text, removed_legacy = remove_legacy_alias_entries(new_text, alias_names)
    removed_count = removed_blocks + removed_legacy
    if removed_count:
        backup = unique_backup(path, ".before-heretic-voxels-uninstall")
        backup.write_text(text, encoding="utf-8")
        path.write_text(new_text, encoding="utf-8")
    return removed_blocks, removed_legacy


def build_package(source_pk3, target_pk3, iwad_path, textures_json):
    with zipfile.ZipFile(source_pk3, "r") as src:
        sprite_names = read_iwad_sprite_names(iwad_path) | pk3_sprite_names(src)
        voxel_names = pk3_voxel_names(src)
        voxel_entries = pk3_voxel_entries(src)
        voxeldef = src.read("VOXELDEF").decode("utf-8", "replace")
        sanitized, aliases, dropped = sanitize_voxeldef(voxeldef, sprite_names, voxel_names)
        aliases.extend((texture_name_for_voxel(name), [name]) for name in voxel_entries)

        try:
            gldefs = src.read("GLDEFS").decode("utf-8", "replace")
        except KeyError:
            gldefs = ""
        gldefs_meta = parse_gldefs_metadata(gldefs)

        target_pk3.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(target_pk3, "w", compression=zipfile.ZIP_DEFLATED) as dst:
            for info in src.infolist():
                if info.filename.upper() == "VOXELDEF":
                    continue
                dst.writestr(info, src.read(info.filename))
            dst.writestr("VOXELDEF", sanitized)

    added_aliases, removed_old_aliases = upsert_texture_aliases(textures_json, aliases, gldefs_meta)
    return dropped, added_aliases, removed_old_aliases


def uninstall(target_dir, textures_json, library):
    alias_names = set()
    removed_files = []

    for name in LOCAL_PK3_NAMES:
        local_pk3 = target_dir / name
        if local_pk3.is_file():
            alias_names.update(collect_alias_names_from_pk3(local_pk3))

    for variant in VARIANTS.values():
        source_pk3 = source_path(library, variant)
        if source_pk3.is_file():
            alias_names.update(collect_alias_names_from_pk3(source_pk3))

    for name in LOCAL_PK3_NAMES:
        local_pk3 = target_dir / name
        if local_pk3.exists() or local_pk3.is_symlink():
            local_pk3.unlink()
            removed_files.append(local_pk3)

    removed_blocks, removed_legacy = remove_texture_aliases(textures_json, alias_names)
    return removed_files, removed_blocks, removed_legacy, len(alias_names)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Install Reikall's Heretic voxel pack through an RT-compatible local wrapper."
    )
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[3]))
    parser.add_argument("--variant", choices=sorted(VARIANTS), default="lite")
    parser.add_argument(
        "--library",
        default=str(default_library()),
        help="External mod library. Defaults to $RT_MODS_DIR or ~/Games/gzdoom-rt/mods.",
    )
    parser.add_argument(
        "--rt-dir",
        default=os.environ.get("RT_DATA_DIR"),
        help="RT data directory. Defaults to <repo-root>/rt.",
    )
    parser.add_argument(
        "--iwad",
        default=str(default_heretic_iwad()),
        help="Heretic IWAD used for sprite-name validation. Defaults to $HERETIC_IWAD or ~/Games/gzdoom-rt/wad/heretic.wad.",
    )
    parser.add_argument(
        "--allow-unknown-checksum",
        action="store_true",
        help="Process a source PK3 whose checksum does not match the recorded recipe version.",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove generated Heretic voxel RT files and this recipe's RT metadata.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    rt_dir = Path(args.rt_dir).resolve() if args.rt_dir else repo_root / "rt"
    iwad_path = Path(args.iwad).expanduser().resolve()
    library = Path(args.library).expanduser().resolve()

    variant = VARIANTS[args.variant]
    source_pk3 = source_path(library, variant)
    target_dir = rt_dir / "autoload" / "heretic"
    target_pk3 = target_dir / f"{source_pk3.stem}-rt.pk3"
    textures_json = rt_dir / "data" / "textures.json"

    if args.uninstall:
        removed_files, removed_blocks, removed_legacy, alias_count = uninstall(target_dir, textures_json, library)
        if removed_files:
            print("Removed generated/local Heretic voxel packages:")
            for path in removed_files:
                print(f"  {path}")
        else:
            print("No generated/local Heretic voxel packages found.")
        if removed_blocks or removed_legacy:
            print(
                "Removed RT metadata for Heretic voxels "
                f"({removed_blocks} marked block(s), {removed_legacy} legacy alias line(s))."
            )
        else:
            print("No Heretic voxel RT metadata found.")
            if alias_count == 0:
                print("No source/generated PK3 was available, so only marked metadata could be detected.")
        return

    if not source_pk3.is_file():
        raise SystemExit(f"Missing source PK3: {source_pk3}")
    if not iwad_path.is_file():
        raise SystemExit(f"Missing Heretic IWAD for VOXELDEF sanitation: {iwad_path}")

    actual_sha = sha256_file(source_pk3)
    if actual_sha != variant["sha256"]:
        message = (
            f"Checksum mismatch for {source_pk3.name}\n"
            f"  expected: {variant['sha256']}\n"
            f"  actual:   {actual_sha}"
        )
        if not args.allow_unknown_checksum:
            raise SystemExit(message + "\nUse --allow-unknown-checksum to process this file anyway.")
        print("Warning: " + message, file=sys.stderr)

    target_dir.mkdir(parents=True, exist_ok=True)
    for stale_name in LOCAL_PK3_NAMES:
        stale = target_dir / stale_name
        if stale.exists() or stale.is_symlink():
            stale.unlink()

    dropped, added_aliases, removed_old_aliases = build_package(source_pk3, target_pk3, iwad_path, textures_json)

    print(f"Sanitized VOXELDEF: dropped {len(dropped)} incompatible entries.")
    for sprites, voxel in dropped[:20]:
        print(f'  dropped {" ".join(sprites)} = "{voxel}"')
    if len(dropped) > 20:
        print(f"  ... {len(dropped) - 20} more")

    if added_aliases:
        print(f"Added {len(added_aliases)} RT material aliases for voxel textures.")
    else:
        print("No new RT material aliases needed for voxel textures.")
    if removed_old_aliases:
        print(f"Replaced {removed_old_aliases} older Heretic voxel RT metadata entry/entries.")

    print(f"Installed sanitized Heretic voxel {args.variant} package:")
    print(f"  {target_pk3}")
    print(f"  source: {source_pk3}")


if __name__ == "__main__":
    main()
